/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorLogin;
import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import letrafantasma.Atributos;
import letrafantasma.FuenteColor;


/**
 *
 * @author esteb
 */
public class Login extends javax.swing.JFrame {

    Atributos mensaje;
    FuenteColor fuentecolor;
    

    /**
     * Creates new form Inicio
     */
    
    
    public Login() {
        initComponents();
        mensaje=new Atributos();
        fuentecolor=new FuenteColor();
      
       
        
        Iniciar ();
        Iniciarpassword();
   
        userText.requestFocus();
        userText.setCaretPosition(0);
        passText.setCaretPosition(0);
        

    }
    
    private  void Iniciar (){
    fuentecolor.mensaje(userText,mensaje.getUsuario(),0);
    fuentecolor.mensaje(passText,mensaje.getPassword(),0);
    }
    
    private  void Iniciarpassword (){
    String mensajeclave =passText.getText();
    if(mensajeclave == null|| mensajeclave.equals("")){
    
        fuentecolor.mensaje(passText,mensaje.getPassword(),0);
        passText.setEchoChar((char )0);
    
    }
    
    
    }
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prime = new javax.swing.JLabel();
        medical = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        iniciar = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exit = new javax.swing.JPanel();
        text_x = new javax.swing.JLabel();
        userText = new javax.swing.JTextField();
        passText = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOlvidar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        returnButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 550));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prime.setForeground(new java.awt.Color(255, 255, 255));
        prime.setText("PRIME MEDICAL");
        getContentPane().add(prime, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 140, 60));

        medical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/prime.png"))); // NOI18N
        medical.setText("jLabel5");
        getContentPane().add(medical, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 220, 180));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Telegram.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 280, 610));

        iniciar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        iniciar.setText("INICIAR SESIÓN");
        getContentPane().add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usuario.setText("USUARIO");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        contraseña.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contraseña.setText("CONTRASEÑA");
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        text_x.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        text_x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_x.setText("X");
        text_x.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        text_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                text_xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                text_xMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text_x, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text_x, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(889, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 40));

        userText.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        userText.setForeground(new java.awt.Color(204, 204, 204));
        userText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                userTextFocusLost(evt);
            }
        });
        userText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTextMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTextMousePressed(evt);
            }
        });
        userText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextActionPerformed(evt);
            }
        });
        userText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userTextKeyTyped(evt);
            }
        });
        getContentPane().add(userText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 490, 20));

        passText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passText.setForeground(new java.awt.Color(204, 204, 204));
        passText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passTextFocusLost(evt);
            }
        });
        passText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passTextMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTextMousePressed(evt);
            }
        });
        passText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTextActionPerformed(evt);
            }
        });
        passText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passTextKeyTyped(evt);
            }
        });
        getContentPane().add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 490, 20));

        btnIngresar.setBackground(new java.awt.Color(40, 50, 253));
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(14, 132, 246), 2, true));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 140, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("¿Olvido la contraseña?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        btnOlvidar.setBackground(new java.awt.Color(40, 50, 253));
        btnOlvidar.setForeground(new java.awt.Color(255, 255, 255));
        btnOlvidar.setText("aqui");
        btnOlvidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlvidarActionPerformed(evt);
            }
        });
        getContentPane().add(btnOlvidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 80, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 60, 60));

        warning.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        getContentPane().add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 190, 20));

        returnButtom.setBackground(new java.awt.Color(40, 50, 253));
        returnButtom.setForeground(new java.awt.Color(255, 255, 255));
        returnButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cerrar-sesion (2).png"))); // NOI18N
        getContentPane().add(returnButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 50, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_xMouseClicked
        System.exit(0);
    }//GEN-LAST:event_text_xMouseClicked

    private void text_xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_xMouseEntered
       text_x.setForeground(Color.white);
       exit.setBackground(Color.red);
    }//GEN-LAST:event_text_xMouseEntered

    private void text_xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_xMouseExited
       text_x.setForeground(Color.gray);
       exit.setBackground(Color.white);
    }//GEN-LAST:event_text_xMouseExited

    private void userTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextMousePressed
       
    }//GEN-LAST:event_userTextMousePressed

    private void passTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTextMousePressed
      
    }//GEN-LAST:event_passTextMousePressed

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
       
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
       
    }//GEN-LAST:event_btnIngresarMouseExited

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void userTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextActionPerformed

    private void btnOlvidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlvidarActionPerformed
  
   
    }//GEN-LAST:event_btnOlvidarActionPerformed

    private void passTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTextActionPerformed

    private void userTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTextFocusLost
        
        fuentecolor.mensaje(userText,mensaje.getUsuario(),userText.getText().trim().length());
    }//GEN-LAST:event_userTextFocusLost

    private void userTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextMouseClicked
        fuentecolor.Click(userText, mensaje.getUsuario());
        userText.setCaretPosition(0);
    }//GEN-LAST:event_userTextMouseClicked

    private void userTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTextKeyTyped
        
        fuentecolor.Click(userText, mensaje.getUsuario());
    }//GEN-LAST:event_userTextKeyTyped

    private void passTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTextFocusLost
      
        Iniciarpassword();
    }//GEN-LAST:event_passTextFocusLost

    private void passTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTextMouseClicked
       fuentecolor.Click(passText, mensaje.getPassword());
       passText.setEchoChar('*');
    }//GEN-LAST:event_passTextMouseClicked

    private void passTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTextKeyTyped
        
        fuentecolor.Click(passText, mensaje.getPassword());
        passText.setEchoChar('*');
    }//GEN-LAST:event_passTextKeyTyped

    private void passTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTextKeyPressed
      passText.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS,java.util.Collections.EMPTY_SET);
      
      if(evt.getKeyCode()==KeyEvent.VK_TAB){
      
        userText.requestFocus();
        userText.setCaretPosition(0);
      
      }
      
      
      
    }//GEN-LAST:event_passTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        Login r = new Login();
        ControladorLogin u = new ControladorLogin(r);
        r.setVisible(true);
        r.setLocationRelativeTo(r);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIngresar;
    public javax.swing.JButton btnOlvidar;
    public javax.swing.JLabel contraseña;
    private javax.swing.JPanel exit;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel iniciar;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel medical;
    public javax.swing.JPasswordField passText;
    private javax.swing.JLabel prime;
    public javax.swing.JButton returnButtom;
    private javax.swing.JLabel text_x;
    public javax.swing.JTextField userText;
    public javax.swing.JLabel usuario;
    public javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
