/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorInventario;
import controlador.ControladorProducto;
import controlador.ControladorProveedor;

/**
 *
 * @author jonathan
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuheader = new javax.swing.JMenuBar();
        menuproducto = new javax.swing.JMenu();
        Vistaproducto = new javax.swing.JMenuItem();
        menuproveedor = new javax.swing.JMenu();
        Vistaproveedor = new javax.swing.JMenuItem();
        menuinventario = new javax.swing.JMenu();
        Vistainventario = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jFrame1.getContentPane().setLayout(new java.awt.BorderLayout());

        jDialog1.getContentPane().setLayout(new java.awt.BorderLayout());

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setMinimumSize(new java.awt.Dimension(608, 82));
        background.setPreferredSize(new java.awt.Dimension(608, 92));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 830, 120));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nombre", "Precio", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1080, 310));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bienvenido");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/prime.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 250, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Cool Sky.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 160));

        menuproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/package-regular-24.png"))); // NOI18N
        menuproducto.setText("Productos");

        Vistaproducto.setBackground(new java.awt.Color(40, 50, 253));
        Vistaproducto.setText("producto");
        Vistaproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaproductoActionPerformed(evt);
            }
        });
        menuproducto.add(Vistaproducto);

        menuheader.add(menuproducto);

        menuproveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/proveedor (1).png"))); // NOI18N
        menuproveedor.setText("Proveedor");

        Vistaproveedor.setBackground(new java.awt.Color(40, 50, 253));
        Vistaproveedor.setText("proveedor");
        Vistaproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaproveedorActionPerformed(evt);
            }
        });
        menuproveedor.add(Vistaproveedor);

        menuheader.add(menuproveedor);

        menuinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/inventario (1).png"))); // NOI18N
        menuinventario.setText("Inventario");

        Vistainventario.setBackground(new java.awt.Color(40, 50, 253));
        Vistainventario.setText("inventario");
        Vistainventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistainventarioActionPerformed(evt);
            }
        });
        menuinventario.add(Vistainventario);

        menuheader.add(menuinventario);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cerrar-sesion (3).png"))); // NOI18N
        jMenu6.setText("cerrar sesion");

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        menuheader.add(jMenu6);

        setJMenuBar(menuheader);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VistaproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaproductoActionPerformed

        Productos r = new Productos();
        ControladorProducto t = new ControladorProducto(r);
        r.setVisible(true);
        r.setLocationRelativeTo(null);
         this.setVisible(false);

    }//GEN-LAST:event_VistaproductoActionPerformed

    private void VistainventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistainventarioActionPerformed
        inventario k = new inventario();
        ControladorInventario c = new ControladorInventario(k);
        k.setVisible(true);
        k.setLocationRelativeTo(null);
        c.listarNombres();
        this.setVisible(false);
                
    }//GEN-LAST:event_VistainventarioActionPerformed

    private void VistaproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaproveedorActionPerformed
           Provedor j = new Provedor();
        ControladorProveedor y = new ControladorProveedor(j);
        j.setVisible(true);
        j.setLocationRelativeTo(null);
         this.setVisible(false);
    }//GEN-LAST:event_VistaproveedorActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        //</editor-fold>

        /* Create and display the form */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Table;
    private javax.swing.JMenuItem Vistainventario;
    private javax.swing.JMenuItem Vistaproducto;
    private javax.swing.JMenuItem Vistaproveedor;
    public javax.swing.JPanel background;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuheader;
    private javax.swing.JMenu menuinventario;
    private javax.swing.JMenu menuproducto;
    private javax.swing.JMenu menuproveedor;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
}
