/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;
import java.awt.BorderLayout;

/**
 *
 * @author jonathan
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        VistaProveedor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VistaInventario = new javax.swing.JButton();
        VistaProductos = new javax.swing.JButton();
        VistaProveedor3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        elements = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        elementos1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VistaProveedor.setBackground(new java.awt.Color(40, 50, 253));
        VistaProveedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        VistaProveedor.setForeground(new java.awt.Color(255, 255, 255));
        VistaProveedor.setText("Proveedores");
        VistaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(VistaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 40, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/prime.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, 294));

        VistaInventario.setBackground(new java.awt.Color(40, 50, 253));
        VistaInventario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        VistaInventario.setForeground(new java.awt.Color(255, 255, 255));
        VistaInventario.setText("Inventario");
        VistaInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(VistaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, -1, 30));

        VistaProductos.setBackground(new java.awt.Color(40, 50, 253));
        VistaProductos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        VistaProductos.setForeground(new java.awt.Color(255, 255, 255));
        VistaProductos.setText("Productos");
        VistaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaProductosActionPerformed(evt);
            }
        });
        getContentPane().add(VistaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, 30));

        VistaProveedor3.setBackground(new java.awt.Color(40, 50, 253));
        VistaProveedor3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        VistaProveedor3.setForeground(new java.awt.Color(255, 255, 255));
        VistaProveedor3.setText("Proveedores");
        VistaProveedor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaProveedor3ActionPerformed(evt);
            }
        });
        getContentPane().add(VistaProveedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 120, -1, 30));

        jLabel3.setText("Cerrar Sesión");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bienvenido");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Cool Sky.png"))); // NOI18N
        jLabel2.setText("H");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 540));

        elements.setText("jLabel5");
        getContentPane().add(elements, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        background.setMinimumSize(new java.awt.Dimension(608, 82));
        background.setPreferredSize(new java.awt.Dimension(608, 92));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 740, 120));

        elementos1.setText("jLabel5");
        getContentPane().add(elementos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nombre", "Precio", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 600, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VistaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaProveedorActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_VistaProveedorActionPerformed

    private void VistaInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VistaInventarioActionPerformed

    private void VistaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VistaProductosActionPerformed

    private void VistaProveedor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaProveedor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VistaProveedor3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
       
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Table;
    public javax.swing.JButton VistaInventario;
    public javax.swing.JButton VistaProductos;
    public javax.swing.JButton VistaProveedor;
    public javax.swing.JButton VistaProveedor3;
    public javax.swing.JPanel background;
    public javax.swing.JLabel elementos1;
    public static javax.swing.JLabel elements;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
}
