/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorProducto;

/**
 *
 * @author jonathan
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Producto
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        ListarProducto = new javax.swing.JButton();
        AgregarProducto = new javax.swing.JButton();
        NombreProducto = new javax.swing.JTextField();
        DescripcionProducto = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        ProveedorProducto = new javax.swing.JComboBox();
        PrecioCompra = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnombreProveedor = new javax.swing.JLabel();
        btnombreProveedor1 = new javax.swing.JLabel();
        Return = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnombreProveedor2 = new javax.swing.JLabel();
        btnombreProveedor3 = new javax.swing.JLabel();
        FechaIngreso = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Proveedor", "Fecha de Ingreso", "PrecioCompra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 600, 220));

        ListarProducto.setBackground(new java.awt.Color(40, 50, 253));
        ListarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ListarProducto.setForeground(new java.awt.Color(255, 255, 255));
        ListarProducto.setText("Listar");
        getContentPane().add(ListarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 100, 30));

        AgregarProducto.setBackground(new java.awt.Color(40, 50, 253));
        AgregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        AgregarProducto.setText("Agregar");
        getContentPane().add(AgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 100, 30));
        getContentPane().add(NombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 96, -1));

        Descripcion.setColumns(20);
        Descripcion.setRows(5);
        DescripcionProducto.setViewportView(Descripcion);

        getContentPane().add(DescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 290, 120));

        ProveedorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorProductoActionPerformed(evt);
            }
        });
        getContentPane().add(ProveedorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, -1));

        PrecioCompra.setText("00000");
        PrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioCompraActionPerformed(evt);
            }
        });
        getContentPane().add(PrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(40, 50, 253));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(40, 50, 253));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/prime.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 180));

        btnombreProveedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnombreProveedor.setText("Nombre");
        getContentPane().add(btnombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, 20));

        btnombreProveedor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnombreProveedor1.setText("Fecha");
        getContentPane().add(btnombreProveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, 20));

        Return.setBackground(new java.awt.Color(40, 50, 253));
        Return.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Return.setForeground(new java.awt.Color(255, 255, 255));
        Return.setText("Return");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        getContentPane().add(Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Cool Sky.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 540));

        btnombreProveedor2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnombreProveedor2.setText("Producto");
        getContentPane().add(btnombreProveedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, -1, 20));

        btnombreProveedor3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnombreProveedor3.setText("PrecioCompra");
        getContentPane().add(btnombreProveedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, 20));

        FechaIngreso.setDateFormatString("yyyy/MM/dd");
        getContentPane().add(FechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProveedorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveedorProductoActionPerformed

    private void PrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioCompraActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        Productos r = new Productos();
        ControladorProducto c = new ControladorProducto(r);
        r.setVisible(true);
        r.setLocationRelativeTo(r);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AgregarProducto;
    public javax.swing.JTextArea Descripcion;
    public javax.swing.JScrollPane DescripcionProducto;
    public com.toedter.calendar.JDateChooser FechaIngreso;
    public javax.swing.JButton ListarProducto;
    public javax.swing.JTextField NombreProducto;
    public javax.swing.JTextField PrecioCompra;
    public javax.swing.JComboBox ProveedorProducto;
    public javax.swing.JButton Return;
    public javax.swing.JTable TablaProducto;
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnEliminar;
    private javax.swing.JLabel btnombreProveedor;
    private javax.swing.JLabel btnombreProveedor1;
    private javax.swing.JLabel btnombreProveedor2;
    private javax.swing.JLabel btnombreProveedor3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
